[versions]

# Kotlin
kotlin = "1.6.20"

# Compose
activity = "1.4.0"
navigation = "2.5.0-alpha04"
compose = "1.2.0-alpha08"


[libraries]

android-pluginGradle = "com.android.tools.build:gradle:7.1.3"
mavenPublish-pluginGradle = "com.vanniktech:gradle-maven-publish-plugin:0.17.0"
metalava-pluginGradle = "me.tylerbwong.gradle:metalava-gradle:0.1.9"
material = "com.google.android.material:material:1.4.0"

# Kotlin

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

# Compose

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-testJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

# Test

androidx-test-core = "androidx.test:core:1.4.0"
androidx-test-rules = "androidx.test:rules:1.4.0"
androidx-test-runner = "androidx.test:runner:1.4.0"
androidx-test-truth = "com.google.truth:truth:1.1.2"
