[versions]

# Kotlin
kotlin = "1.8.22"

# Compose
activity = "1.7.2"
navigation = "2.6.0"
compose = "1.5.0"
composeCompiler = "1.4.8"

# AndroidX

tracing = "1.1.0"

[libraries]

android-pluginGradle = "com.android.tools.build:gradle:8.0.2"
mavenPublish-pluginGradle = "com.vanniktech:gradle-maven-publish-plugin:0.17.0"
metalava-pluginGradle = "me.tylerbwong.gradle.metalava:plugin:0.3.2"

# Kotlin

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

dokka-pluginGradle = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.10"

# Compose

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-testJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

# AndroidX

androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "tracing" }

# Test

androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-truth = "com.google.truth:truth:1.1.5"
